### PR TITLE
feat: text area component

### PR DESCRIPTION
**Pull request by tamrivera05**

### CODE REVIEW

**Comment by tamrivera05** [comment]
* **#17** <a href="https://app.graphite.dev/github/pr/TimBuilding/Elysseum/17?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#16** <a href="https://app.graphite.dev/github/pr/TimBuilding/Elysseum/16?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#15** <a href="https://app.graphite.dev/github/pr/TimBuilding/Elysseum/15?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#8** <a href="https://app.graphite.dev/github/pr/TimBuilding/Elysseum/8?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#7** <a href="https://app.graphite.dev/github/pr/TimBuilding/Elysseum/7?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tamrivera05 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by xdjeremy** [comment]
[confused](https://app.graphite.dev//settings/meme-library?org=TimBuilding)

**Review by xdjeremy — CHANGES_REQUESTED** [review]
[ci](https://app.graphite.dev//settings/meme-library?org=TimBuilding)

**Comment by tamrivera05** [comment]
bat nadelete hmp

**Review by xdjeremy — CHANGES_REQUESTED** [review]
may conflict padin
[fixit](https://app.graphite.dev//settings/meme-library?org=TimBuilding)

**Comment by tamrivera05** [comment]
k na >:(

**Review by xdjeremy — APPROVED** [review]
[birdbox](https://app.graphite.dev//settings/meme-library?org=TimBuilding)

**Pull request merged**
